### ISSUE TITLE
Error when deploying a package

### ISSUE THREAD

**Issue by arabold** [FidelLimited/serverless-plugin-warmup#20]
The plugin seems to work fine and as expected if I run a `serverless deploy` to package and deploy everything in one step. However, on our build server we split this in two distinct steps: build and deployment. During the build we run a `serverless package` and then, once we want deploy, a `serverless deploy --package=...` using the already packaged archive. This worked fine in the 2.1.0 release we used before, but seems to be broken in 3.0.2 now. 

The following exception in thrown:
```
TypeError: Cannot read property 'prewarm' of undefined
    at WarmUP.afterDeployFunctions (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless-plugin-warmup/src/index.js:80:20)
    at BbPromise.reduce (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.run (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/lib/classes/PluginManager.js:273:17)
    at variables.populateService.then (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/lib/Serverless.js:105:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/lib/Serverless.js:92:74)
    at serverless.init.then (/var/atlassian/application-data/bamboo/xml-data/build-dir/100040705-100106241/node_modules/serverless/bin/serverless:30:50)
```

There's no specific configuration in our `serverless.yml` other than `warmup: true` for a couple of functions.

This issue was most likely introduced due to new pre-warm feature in @juanjoDiaz's PR #16

**Comment by goncaloneves** [comment]
Thanks for reporting @arabold. 👍 Closed by #21.
