### ISSUE TITLE
Instructions on getting warmup to work with serverless-webpack

### ISSUE THREAD

**Issue by damonmaria** [FidelLimited/serverless-plugin-warmup#6]
I preface this with the fact that I'm a webpack newbie so this may be suboptimal. 

If using the `serverless-webpack` plugin then you need to make some changes to `webpack.config.js` to get `serverless-plugin-warmup` to work.

1. Add a new chunk for warmup with the specific path that the warmup plugin uses. 
2. Add an `output` section as per above. This ensures that the warmup handler is appears in the bundle at the same path as it would have originally.

For example:
```js
  entry: {
    handler: [/* possibly other entry points like babel-polyfill, ... */ './handler.js'],
    '_warmup/index': './_warmup/index.js',
  },
  output: {
    libraryTarget: 'commonjs',  // <- as per serverless-webpack README
    path: '.webpack',
    filename: '[name].js',
  },
```

An issue with this setup is that `serverless webpack invoke` no longer works because `_warmup` does not exist then. 

Another potential issue is the reliance on the `_warmup/index.js` path not changing.

**Comment by mikestaub** [comment]
@damonmaria I simply copy the whole _warmup dir with copy-webpack-plugin like so:

`plugins: [new CopyWebpackPlugin({ from: '_warmup', to: '_warmup' })],`

**Comment by damonmaria** [comment]
@mikestaub That's much smarter than what I had. I did have to pass an array into the plugin tho:
```js
  plugins: [
    new CopyWebpackPlugin([{ from: '_warmup', to: '_warmup' }]),
  ],
```

**Comment by dscis** [comment]
Keep getting Unable to import module '_warmup/index': Error at require (internal/module.js:20:19)
Regardless what method I use either the copywebpackplugin or object entry

**Comment by goncaloneves** [comment]
@dscis I don't use webpack plugin, so I can't troubleshoot this for you.
The best thing for you to is open an issue on their repo and speak with someone who uses both together.

**Comment by lucasklaassen** [comment]
@damonmaria @mikestaub  is this implementation still working for you? After following your steps to use the `CopyWebpackPlugin` I'm receiving the following error when trying to deploy:

```
Error: ENOENT: no such file or directory, open '.webpack/.serverless/warmUpPlugin.zip'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at AwsCompileFunctions.compileFunction (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:292:24)
    at serverless.service.getAllFunctions.forEach (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:334:39)
    at Array.forEach (native)
    at AwsCompileFunctions.compileFunctions (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:334:8)
    at BbPromise.reduce (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/Users/development/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by lucasklaassen** [comment]
For anyone else that finds this thread, the following webpack.config.js works for me now:
```
const nodeExternals = require('webpack-node-externals');
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, '.webpack'),
    filename: '[name].js' // this should match the first part of function handler in serverless.yml
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ["babel-loader"]
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  }
};
```

serverless: `1.24.1`
serverless-plugin-warmup: `3.3.0-rc.1`
serverless-webpack: `4.0.0`
webpack: `4.0.0`

**Comment by coderkk1992** [comment]
Error:
Error: Error: Error: ENOENT: no such file or directory, open '/Users/kalithk/Desktop/billion/fitcorp/fitclub-backend/.build/.serverless/warmUpPluginDefault.zip' encountered during hash calculation for provided filePath: /Users/kalithk/Desktop/billion/fitcorp/fitclub-backend/.build/.serverless/warmUpPluginDefault.zip
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/lib/get-hash-for-file-path.js:23:13)
    at ReadStream.emit (node:events:513:28)
    at ReadStream.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

I'm getting this. I'm not even using webpack

**Comment by juanjoDiaz** [comment]
Hi @coderkk1992,

I need a projects where I can reproduce the issue and then I can look into it 🙂
